### PR TITLE
Update with Important(tm) info

### PR DESCRIPTION
**Pull request by amanogawa01**

### CODE REVIEW

**Comment by queer** [comment]
Fake news.

**Review by spotlightishere — APPROVED** [review]

**Comment by queer** [comment]
This also does not render correctly. Check the deploy preview.

**Comment by queer** [comment]
@Faith1sGay Are you planning to fix this?

**Comment by amanogawa01** [comment]
> @Faith1sGay Are you planning to fix this?

yes. I've just been busy ;-;

**Comment by queer** [comment]
@Faith1sGay As there's been no activity in 4 months, I'm closing this.

**Pull request closed without merging**
